spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password: ""
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
      indent-output: true
      fail-on-unwrapped-type-identifiers: false
    default-property-inclusion: non-null
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
      
            
