spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test;MODE=MYSQL
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect