spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: 
    password: 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.hibernate: info
    org.hibernate.type.descriptor.sql: trace
     
