spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    default-property-inclusion: non-null
    property-naming-strategy: SNAKE_CASE
      
