spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
    username: sa
    password:
  #    hikari:
  #      jdbc-url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      format_sql: true
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #storage_engine: innodb
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2