spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password: ""
  jpa:
#    properties: hibernate.ejb.interceptor: kr.co.ant.study.jpa.basic.AuditDirtyCheckingInterceptor
    generate-ddl: true
    hibernate:
     ddl-auto: create
logging:
  level:
    org.hibernate: info
    org.hibernate.type.descriptor.sql: trace     